kind: Service
apiVersion: v1
metadata:
  name: spring-boot-app-service
spec:
  selector:
    app: springboot-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
